apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mkj-cisc-app-ui
  name: mkj-cisc-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkj-cisc-app-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mkj-cisc-app-ui
    spec:
      containers:
      - image: manajena/mkjapp:v1
        name: mkjapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
